### ISSUE TITLE
Not open sourced if destrucion sim.lua is still obfuscated lol

### ISSUE THREAD

**Issue by yofriendfromschool1** [BirthScripts/starhook#1]
Not open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lolNot open sourced if destrucion sim.lua is still obfuscated lol
Not open sourced if destrucion sim.lua is still obfuscated lol
Not open sourced if destrucion sim.lua is still obfuscated lol
Not open sourced if destrucion sim.lua is still obfuscated lol

**Comment by BirthScripts** [comment]
why do u care
